receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  clickhouse:
    endpoint: tcp://clickhouse:9000?database=default
  otlp/signoz:
    endpoint: signoz-otel-collector:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp/signoz]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, otlp/signoz]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp/signoz]

